### ISSUE TITLE
게임 진행중 답 쓰는 칸이 일정하지 않습니다. 

### ISSUE THREAD

**Issue by DongJoon-Lee** [Lee-SungMin/ERICA_ChoSung#2]
어떤 문제에서는 답을 쓰는 칸 자체가 작고, 또 다른 칸에서 커집니다. 
답을 쓰는 칸이 일정하지 않은 것 같은데, 값을 수정해서 맞추는게 더 보기 좋을 것 같습니다!

**Comment by Lee-SungMin** [comment]
수정했어요!!
감사합니다~~
